#!/usr/bin/perl -w
use strict;

my $ref_table = shift;	# the table generated by analyzing HMMER3 results using SummarizeHmmerResults.pl

my %region_annot;
open my $IN, "<$ref_table" or die "Cannot open file: $!\n";
while(<$IN>)  {
  chomp;
  my @decom = split /\s+/, $_;
  my @decom2 = split /\_/, $decom[1];
  # converting the indexes
  my $begin;
  my $end;
  my $strand_id = scalar(@decom2) - 1;
  my $rend_id = scalar(@decom2) - 2;
  my $rbegin_id = scalar(@decom2) - 3;
  my $info_str = $decom2[$rbegin_id] . '_' . $decom2[$rend_id] . '_' . $decom2[$strand_id];
  $decom[1] =~ /(.*)\_$info_str/;
  my $target_id = $1;
  if($decom2[$strand_id] eq '+')  {
    $begin = $decom2[$rbegin_id] + 3 * ($decom[4] - 1);
    $end = $begin + ($decom[5] - $decom[4]) * 3 - 1;
  }  elsif($decom2[$strand_id] eq '-')  {
    $end = $decom2[$rend_id] - 3 * ($decom[4] - 1);
    $begin = $end - ($decom[5] - $decom[4]) * 3 + 1;
  }
  print "$decom2[0]	$begin	$end	$decom[0]	0	$decom2[3]\n";
}
close $IN;

