#!/usr/bin/perl -w
use strict;

my $file = shift;		# the file generated by ScriptRepo/JoinFilesByKey.pl
my $out = shift;		# the output file

# the column ID contains the gi|xxxx information
my $col = 12;
# the gi ID to taxa ID mapping file, downloaded from NCBI website
my $gi_to_taxa = "/usr/local/projdata/0599/projects/SPA/czhong/Data/NCBI_taxanomy/gi_taxid_prot.dmp";		
# the taxa ID to taxa name mapping file, downloaded from NCBI website
my $taxa_to_name = "/usr/local/projdata/0599/projects/SPA/czhong/Data/NCBI_taxanomy/names.dmp";

if(!defined $file || !defined $out)  {
  print "Usage: perl map_taxanomy.pl [JOINED_FILE] [OUTPUT]\n";
  print "The JOINED_FILE contains rows like the following:\n";
  print "NODE_73_length_312_cov_2.36576_ID_145	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	gi|557843874|ref|WP_023466719.1|	99.04	104	1	0	1	312	131	234	3e-63	204	204\nNODE_83_length_294_cov_2.71967_ID_165	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	gi|446963889|ref|WP_001041145.1|	98.97	97	1	0	291	1	171	267	8e-59	193	193\nNODE_89_length_282_cov_1.9207_ID_177	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	gi|639751403|ref|WP_024733586.1|	67.02	94	31	0	282	1	150	243	3e-37	136	136\n";
  exit;
} 

open my $OUT, ">$out" or die "Cannot create file for output: $!\n";

print "NOTE: using GI_ID<->TAXA_ID mapping file $gi_to_taxa\n";
print "NOTE: using TAXA_ID<->TAXA_NAME mapping file $taxa_to_name\n";
print "NOTE: using 12 as the column ID that contains the gi number (with format like gi|xxxx|ref|xxxx)\n";

my %info_hash;
my %taxa_hash;
my %name_hash;
open my $FIN, "<$file" or die "Cannot open file: $!\n";
while(<$FIN>)  {
  chomp;
  my $line = $_;
  my @decom = split /\s+/, $_;
  my @decom2 = split  /\|/, $decom[$col];
  $info_hash{$decom2[1]} = $line;
}
close $FIN;

open my $TIN, "<$gi_to_taxa" or die "Cannot open file: $!\n";
while(<$TIN>)  {
  chomp;
  my @decom = split /\s+/, $_;
  if(exists $info_hash{$decom[0]})  {
    $taxa_hash{$decom[0]} = $decom[1];
    $name_hash{$decom[1]} = 1;
  }
}
close $TIN;

open my $NIN, "<$taxa_to_name" or die "Cannot open file: $!\n";
while(<$NIN>)  {
  chomp;
  my @decom = split /\s*\|\s*/, $_;
  #print "!$decom[0]	!$decom[1]	!$decom[2]	!$decom[3]\n";
  $name_hash{$decom[0]} = $decom[1] if (exists $name_hash{$decom[0]} and $decom[3] eq "scientific name");
}
close $NIN;

foreach(keys %info_hash)  {
  print $OUT "$_	$name_hash{$taxa_hash{$_}}	$info_hash{$_}\n";
}
close $OUT;
