#!/usr/bin/perl -w
use strict;
use Cwd 'abs_path';

my $folder = shift;		# expected to be the evaluation folder generated by EvalHMMGRASPx_pipeline.pl
$folder = abs_path($folder);

my $data = "/usr/local/projdata/0599/projects/SPA/czhong/Data/saliva.faa";
my $script_dir = "/usr/local/projdata/0599/projects/SPA/czhong/Works/GRASPxp/Scripts";
my $Hmmer_dir = "/home/czhong/Tools/hmmer-3.1b2-linux-intel-x86_64";
my $SPA_dir = "/home/czhong/Tools/sfaspa-0.2.0";

print "EVALUATING HMM-GRASPXP PERFORMANCE......\n";
# pull out the ID first
#system "cat $folder/HMMGRASPx_out/recruited.list \| awk \'{print \$2}\' >$folder/graspxp.list";
# get the sequence using the ID
#system "perl /home/czhong/ScriptRepo/GetFastaSeqByID.pl --fasta=$data --id=$folder/graspxp.list --out=$folder/graspxp.fa";
# perform SFA-SPA assembly
#system "perl $SPA_dir/script/run_spa.pl -i $folder/graspxp.fa -s 1 -o $folder/SPA_graspxp -S 1 -r 1 -n 8";
# using hmmsearch to validate the contigs
#system "$Hmmer_dir/binaries/hmmsearch $folder/model.hmm $folder/SPA_graspxp/spa.fasta >$folder/graspxp.spa.results";
# verify the performance for this program
system "perl $script_dir/parse_spa_results.pl $folder/graspxp.fa $folder/graspxp.spa.results $folder/SPA_graspxp";

print "EVALUATING HMMER3 PERFORMANCE......\n";
# get mapped reads
#system "perl $script_dir/hmmer3_to_graspxp_map.pl $folder/hmmsearch.raw 0.01 >$folder/hmmsearch.map";
# pull out the ID first
#system "cat $folder/hmmsearch.map \| awk \'{print \$2}\' >$folder/hmmsearch.list";
# get the sequence using the ID
#system "perl /home/czhong/ScriptRepo/GetFastaSeqByID.pl --fasta=$data --id=$folder/hmmsearch.list --out=$folder/hmmsearch.fa";
# perform SFA-SPA assembly
#system "perl $SPA_dir/script/run_spa.pl -i $folder/hmmsearch.fa -s 1 -o $folder/SPA_hmmsearch -S 1 -r 1 -n 8";
# using hmmsearch to validate the contigs
#system "$Hmmer_dir/binaries/hmmsearch $folder/model.hmm $folder/SPA_hmmsearch/spa.fasta >$folder/hmmsearch.spa.results";
# verify the performance for this program
system "perl $script_dir/parse_spa_results.pl $folder/hmmsearch.fa $folder/hmmsearch.spa.results $folder/SPA_hmmsearch";

print "EVALUATING RPS-BLAST PERFORMANCE......\n";
# get mapped reads
#system "perl $script_dir/rpsblast_to_map.pl $folder/smp.list $folder/rps.raw 0.00001 >$folder/rps.map";
# pull out the ID first
#system "cat $folder/rps.map \| awk \'{print \$2}\' >$folder/rpsblast.list";
# get the sequence using the ID
#system "perl /home/czhong/ScriptRepo/GetFastaSeqByID.pl --fasta=$data --id=$folder/rpsblast.list --out=$folder/rpsblast.fa";
# perform SFA-SPA assembly
#system "perl $SPA_dir/script/run_spa.pl -i $folder/rpsblast.fa -s 1 -o $folder/SPA_rpsblast -S 1 -r 1 -n 8";
# using hmmsearch to validate the contigs
#system "$Hmmer_dir/binaries/hmmsearch $folder/model.hmm $folder/SPA_rpsblast/spa.fasta >$folder/rpsblast.spa.results";
# verify the performance for this program
system "perl $script_dir/parse_spa_results.pl $folder/rpsblast.fa $folder/rpsblast.spa.results $folder/SPA_rpsblast";

print "EVALUATING UProC PERFORMANCE......\n";
# pull out the ID first
#system "cat $folder/uproc.full.map \| awk \'{print \$2}\' >$folder/uproc.list";
# get the sequence using the ID
#system "perl /home/czhong/ScriptRepo/GetFastaSeqByID.pl --fasta=$data --id=$folder/uproc.list --out=$folder/uproc.fa";
# perform SFA-SPA assembly
#system "perl $SPA_dir/script/run_spa.pl -i $folder/uproc.fa -s 1 -o $folder/SPA_uproc -S 1 -r 1 -n 8";
# using hmmsearch to validate the contigs
#system "$Hmmer_dir/binaries/hmmsearch $folder/model.hmm $folder/SPA_uproc/spa.fasta >$folder/uproc.spa.results";
# verify the performance for this program
system "perl $script_dir/parse_spa_results.pl $folder/uproc.fa $folder/uproc.spa.results $folder/SPA_uproc";

