#!/usr/bin/perl -w
use strict;

my $mfasta_file = shift;	# the original multi-FASTA read file generated by FragGeneScan
my $listID_file = shift;	# the read-recruitment file generated by GRASP
my $cutoff = shift;		# the e-value cutoff for the recruitment

my %id_hash;
open my $IN, "<$listID_file" or die "Cannot open file: $!\n";
while(<$IN>)	{
	chomp;
	my @decom = split /\s+/, $_;
	$id_hash{$decom[1]} = $decom[2];
}
close $IN;

my $id = 0;
open my $RIN, "<$mfasta_file" or die "Cannot open file: $!\n";
while(<$RIN>)	{
	chomp;
	if(/^>/)	{
		my $header = $_;
		my $sequence = <$RIN>;
		chomp $sequence;
		if(exists $id_hash{$id} && $id_hash{$id} < $cutoff)	{
			print "$header\n$sequence\n";
		}		
		++ $id;
	}
}
close $RIN;

