#!/usr/bin/perl -w
use strict;

my $galn_file = shift;	# the alignment file generated by GRASP
open my $IN, "<$galn_file" or die "Cannot open file: $!\n";

my @contents;
while(<$IN>)	{
	chomp;
	push @contents, $_;
}
close $IN;

my $i;
my $id = 0;
for($i = 0; $i < scalar(@contents); ++ $i)	{
	if($contents[$i] =~ /ALIGNMENT\s+BEGINS/)	{
		my $acc_seq = "";
		my $read_report;
		my $target_begin = $i + 6;
		# get the e-value
		$contents[$i + 2] =~ /Evalue\:\s+(.*)/;
		my $evalue = $1;
		# jump to the read report
		while(!($contents[$i] =~ /included\s+reads/))	{
			++ $i;
		}
		my $target_end = $i;
		$read_report = $contents[$i + 1];
		while($target_begin < $target_end)	{
			$contents[$target_begin] =~ s/\s+//g;
			$contents[$target_begin] =~ s/\-//g;
			$acc_seq .= $contents[$target_begin];
			$target_begin += 4;
		}
		print ">assembled_sequence:$id\t$evalue\t$read_report\n";
		print "$acc_seq\n";
		++ $id;
	}
}
