#!/usr/bin/perl -w
use strict;

my $mfasta_file = shift;	# the original multi-FASTA read file generated by FragGeneScan
my $listID_file = shift;	# the results generated by blastp
my $cutoff = shift;		# the e-value cutoff for the recruitment

my %id_hash;
open my $IN, "<$listID_file" or die "Cannot open file: $!\n";
while(<$IN>)	{
	if(/^\#/)	{
		next;
	}
	chomp;
	my @decom = split /\s+/, $_;
	$id_hash{$decom[1]} = $decom[10];
	#print "$decom[1]	$decom[10]\n";
}
close $IN;

#exit;

my $id = 0;
open my $RIN, "<$mfasta_file" or die "Cannot open file: $!\n";
while(<$RIN>)	{
	chomp;
	if(/^>(.*)/)	{
		my $header = $_;
		my $header_core = $1;
		my $sequence = <$RIN>;
		chomp $sequence;
		if(exists $id_hash{$header_core} && $id_hash{$header_core} < $cutoff)	{
			print "$header\n$sequence\n";
		}		
		++ $id;
	}
}
close $RIN;

